/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsEntity {
  entityType: string
  value: string
  start: number
  end: number
}
export interface JsAnonymizationResult {
  anonymizedText: string
  mapping: Record<string, string>
  entities: Array<JsEntity>
}
export declare class JsAnonymizer {
  constructor(entityTypes: Array<string>)
  anonymize(text: string): JsAnonymizationResult
  deanonymize(text: string, mapping: Record<string, string>): string
}
