/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Entity {
  entityType: string
  value: string
  start: number
  end: number
}
export interface AnonymizationResult {
  anonymizedText: string
  mapping: Record<string, string>
  entities: Array<Entity>
}
export declare class Anonymizer {
  constructor(entityTypes: Array<string>)
  anonymize(text: string): AnonymizationResult
  deanonymize(text: string, mapping: Record<string, string>): string
}
